import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const poppinsMono = Poppins({
  variable: "--font-poppins-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "DiHy Care",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${poppinsMono.variable} antialiased flex bg-[#d9d9d9] h-screen overflow-hidden`}
      >
        {/* 🔹 Sidebar visible en todas las páginas */}
        <Sidebar />

        {/* 🔹 Contenido principal */}
        <main className="flex-1 overflow-y-hidden">{children}</main>
      </body>
    </html>
  );
}
